spring:
  datasource:
    url: jdbc:mysql://15.164.85.142:3306/freelancer_service
    username: admin
    password: admin123!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
    host: 15.164.85.142
    port: 6379
    password: redis123!!
  mail:
    host: smtp.gmail.com
    port: 587
    username: freelancer.service.platform@gmail.com
    password: ptin kuad wzoy hlen
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB 컬럼명(user_sq) ↔ Java 필드(userSq) 자동 매핑

server:
  port: 8080
  # address: 0.0.0.0  # 배포 시 외부 접속 허용 시 사용
  servlet:
    context-path: /api # ← 공백으로 들여쓰기 확인!

logging:
   level:
    org.mybatis: DEBUG
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG

