spring:
  datasource:
    url: jdbc:p6spy:mysql://15.164.85.142:3306/freelancer_service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: admin123!!
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  data:
    redis: # ← 여기 들여쓰기 수정됨
      host: 15.164.85.142
      port: 6379
      password: redis123!!

  mail:
    host: smtp.gmail.com
    port: 587
    username: freelancer.service.platform@gmail.com
    password: ptin kuad wzoy hlen
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    active: dev #

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  # address: 0.0.0.0
  servlet:
    context-path: /api

jwt:
  secret: MySuperSecretKeyForJWTEncoding123456
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

# 기업 인증 API
external:
  business-verify:
    api-key: oo7Cptu/muq0VdvJOvEZ816dEyBChjhrqLIM0HqL2+eJeZXKg46MztkspSRsh3HBX/lyqoXbNCWB4OydznQ+mg== #

logging:
  level:
    root: INFO
    # org.hibernate.SQL: DEBUG # JPA SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩된 파라미터 출력
    # org.mybatis: DEBUG # MyBatis SQL 출력
    com.zaxxer.hikari: DEBUG # 커넥션풀 관련 로그
